<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/permission/resource" class="active">Resource List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
               Resource List
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> items 
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable  table-sortable" id="post-grid" data-sortable-key="order" data-sortable-default="-created_at">
                    <thead>
                        <tr>
                            <th class="hidden-480">
                                ID
                            </th>
                            <th>Group</th>
                            <th>Name</th>
                            <th>Key</th>
                            <th>Description</th>
                            <th>Operations</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        <?foreach($pager->items as $item):?>
                        <tr>
                            <td class="hidden-480"><?=$item->id?></td>
                            <td><span class="label"><?=$item->resourceGroup?></span></td>
                            <td>
                                <?=$item->name?>
                            </td>
                            <td><span class="label"><?=$item->resourceKey?></span></td>
                            <td><?=$item->description?></td>
                            <td>
                                <a class="btn btn-xs btn-info" href="/admin/permission/operation?q=<?=$this->escaper->escapeHtmlAttr(addslashes($item->resourceKey))?>">
                                        <i class="icon-wrench  bigger-120"></i>
                                        <?=$item->operations ? $item->operations->count() : '0'?> Operations
                                    </a>
                            </td>
                            <td>
                                <div class="btn-group">

                                </div>
                            </td>
                        </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/permission/resource',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
