<div class="breadcrumbs" id="breadcrumbs">
    <script type="text/javascript">
        try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
    </script>

    <ul class="breadcrumb">
        <li>
        <i class="icon-home home-icon"></i>
        <a href="/admin/dashboard">Home</a>
        </li>

        <li>
        <a href="/admin/permission/apikey" class="active">Key List</a>
        </li>
    </ul><!-- .breadcrumb -->

    <div class="nav-search" id="nav-search">
        <form class="form-search">
            <span class="input-icon">
                <input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
                <i class="icon-search nav-search-icon"></i>
            </span>
        </form>
    </div><!-- #nav-search -->
</div>

<div class="page-content">

    <div class="row">
        <div class="col-xs-12">
            <h3 class="header smaller lighter blue">
               Key List
               <a href="/admin/permission/apikey/create" class="btn btn-sm"><i class="icon-group align-top bigger-125"></i> Generate New Key</a>
            </h3>
            <div class="table-header">
                Showing <?=$pager->offset_start?> to <?=$pager->offset_end?> of <?=$pager->total_items?> items 
            </div>

            <div class="table-responsive dataTables_wrapper">
                <div class="row">
                    <div class="col-sm-12">
                    </div>
                </div>
                <table class="table table-striped table-bordered table-hover dataTable  table-sortable" id="post-grid" data-sortable-key="order" data-sortable-default="-created_at">
                    <thead>
                        <tr>
                            <th class="hidden-480">
                                ID
                            </th>
                            <th>Key</th>
                            <th>User</th>
                            <th>Minutely Rate</th>
                            <th>Hourly Rate</th>
                            <th>Daily Rate</th>
                            <th>Created At</th>
                            <th>Expired At</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        <?foreach($pager->items as $item):?>
                        <tr>
                            <td class="hidden-480"><?=$item->id?></td>
                            <td>
                                <a href="/admin/permission/apikey/<?=$item->id?>"><code><?=$item->apikey?></code></a>
                                <span class="label"><?=$item->level?></span>
                            </td>
                            <td><a href="/admin/user/edit/<?=$item->user->id?>"><?=$item->user->username?></a></td>
                            <td><?=$item->minutelyRate?></td>
                            <td><?=$item->hourlyRate?></td>
                            <td><?=$item->dailyRate?></td>
                            <td><?=$this->tag->datetime($item->createdAt)?></td>
                            <td><?=$item->expiredAt > 0 ? $this->tag->datetime($item->expiredAt) : 'Never'?></td>
                            <td>
                                <div class="btn-group">
                                    <button class="btn btn-xs btn-success ajax-form-sumbit" data-ajax-form="1" date-method="put" data-form-action="/admin/permission/process/apikey/<?=$item->id?>" data-callback="window.location.reload();">
                                        <i class="icon-key bigger-120"></i> Change Key
                                    </button>
                                    <a class="btn btn-xs btn-info" href="/admin/permission/apikey/edit/<?=$item->id?>">
                                        <i class="icon-edit bigger-120"></i> Change Plan
                                    </a>
                                </div>
                            </td>
                        </tr>
                        <?endforeach?>
                    </tbody>
                </table>

                <div class="row">
                    <div class="col-sm-6">
                    </div>
                    <div class="col-sm-6">
                        <div class="dataTables_paginate">
                            <?$this->partial("partial/paginator", array(
                                'pagerUrl' => '/admin/permission/apikey',
                                'pager' => $pager,
                            ))?>
                        </div>
                    </div>
                </div>

            </div><!--/table div-->

        </div><!-- /col-->
    </div><!--row end-->

</div><!-- /.page-content -->
